### ISSUE TITLE
Some questions about the SCSS

### ISSUE THREAD

**Issue by jhubert** [davidkpiano/react-simple-datepicker#1]
Nice work on the simple date component. Most of the solutions out there are far more complex than necessary.

Two questions about the CSS:
- the `.sd-datepicker` selector includes the style reset rules that are already included in the `_reset` file. Why the duplication? Is it to counter any issues with the Lato font?
- In `_colors` you define a `primary-color` but in `_variables` you define a `colors` map. Any reason for having both?

**Comment by davidkpiano** [comment]
Thanks @jhubert, and good questions!
1. The duplication isn't necessary - one of them can be removed (or both, if you are using a reset stylesheet such as **normalize.css**). They can be in either location, depending on:
   - If this component is meant to be dropped in as a 3rd-party component (in which case, scope it to `.sd-datepicker`
   - If this component is part of the project's bespoke components (in which case, you can safely globally apply the reset styles in `_reset.scss`).
2. That's my mistake - per @hugogiraudel's 7-1 architecture, variables should be defined in the `utils/` directory, under `_variables.scss` or `_colors.scss`. I'll remove it from the base directory.
