### ISSUE TITLE
Pure Component

### ISSUE THREAD

**Issue by ximet** [davidkpiano/react-simple-datepicker#4]
Why you not use pure component? I think, it's better way for not rendering each time a component, if it's not necessary.

**Comment by davidkpiano** [comment]
Because this was a sample project made for an article 2 years ago 😉

**Comment by ximet** [comment]
@davidkpiano Why you won't update to solution? I think, it's component has the right to life =)

**Comment by davidkpiano** [comment]
> Why you won't update to solution? 

Why won't _you_? You're more than welcome to submit a PR, and I will happily accept it. That's what open source is about.

**Comment by adamkarb** [comment]
* [ ] Not rekt
* [x] Tyranosaurus rekt
